project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Team"
        contents:
          - team.qmd
      - section: "Student applications 2023"
        contents:
          - projects_2023.qmd 
          - student_app.qmd 
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

