project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "OneZoo Home"
        contents:
          - index.qmd
      - section: "Team"
        contents:
          - team.qmd
      - section: "Project Applications 2024"
        contents:
          - faqs.qmd 
          - faqs_annex_a.qmd 
          - faqs_annex_b.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

